[Service]
PrivateUsers=no
SystemCallFilter=
ProtectProc=default
ProcSubset=all
ReadWritePaths=%h/.config/activitywatch/aw-notify
ReadWritePaths=%h/.cache/activitywatch/aw-notify
ReadWritePaths=%h/.cache/activitywatch/client_locks
